# Generated by Django 3.0 on 2019-12-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('release_name', models.CharField(max_length=100)),
                ('bpm', models.CharField(max_length=160)),
                ('release_date', models.CharField(max_length=175)),
            ],
        ),
    ]
