# Generated by Django 3.0 on 2019-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleiner_specht', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_genre', models.CharField(max_length=200)),
            ],
        ),
    ]
